// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: DefaultServiceException.vsl in andromda-spring-cartridge.
//
package com.ten45.service.aggregator;

/**
 * The default exception thrown for unexpected errors occurring
 * within {@link com.ten45.service.aggregator.ConfigurationService}.
 */
@SuppressWarnings("serial")
public class ConfigurationServiceException
    extends com.ten45.basic.KeyedException
{

    /**
     */
    public ConfigurationServiceException( Key key )
    {
        super( key );
    }

    /**
     */
    public ConfigurationServiceException( Key key, Throwable t )
    {
        super( key, t );
    }

    /**
     */
    public ConfigurationServiceException( Key key, Object[] arguments )
    {
        super( key, arguments );
    }

    /**
     */
    public ConfigurationServiceException( Key key, Object[] arguments, Throwable t )
    {
        super( key, arguments, t );
    }

    /**
     * Constructs a new instance of <code>ConfigurationServiceException</code>.
     *
     * @param throwable the parent Throwable
     */
    public ConfigurationServiceException(Throwable throwable)
    {
        super(findRootCause(throwable));
    }

    /**
     * Constructs a new instance of <code>ConfigurationServiceException</code>.
     *
     * @param message the throwable message.
     */
    public ConfigurationServiceException(String message)
    {
        super(message);
    }

    /**
     * Constructs a new instance of <code>ConfigurationServiceException</code>.
     *
     * @param message the throwable message.
     * @param throwable the parent of this Throwable.
     */
    public ConfigurationServiceException(String message, Throwable throwable)
    {
        super(message, findRootCause(throwable));
    }

}