// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringService.vsl in andromda-spring-cartridge.
//
package com.ten45.service.aggregator;

/**
 * <p>
 * Handles configuration.
 * </p>
 */
public interface ConfigurationService
{

    /**
     * <p>
     * Find configuration info for a merchant.
     * </p>
     */
    public java.lang.Object findConfiguration(java.lang.String merchantName);

    /**
     * <p>
     * Return a ftp parameter object by name.
     * </p>
     */
    public com.ten45.service.aggregator.FtpParameter findFtpParameter(java.lang.String groupBy);

    /**
     * 
     */
    public java.util.List<com.ten45.entity.aggregation.CrawlSessionImpl> loadCrawlSessions();

    /**
     * <p>
     * Save the CrawlSession and it's child crawledElements to
     * database.
     * </p>
     */
    public void saveCrawlSession(com.ten45.entity.aggregation.CrawlSession crawlSession);

    /**
     * 
     */
    public java.lang.Long discoverCrawlSessions(java.util.List<com.ten45.entity.aggregation.CrawlSessionImpl> crawlSessions);

    /**
     * 
     */
    public void clearCrawlSessionElements(com.ten45.entity.aggregation.CrawlSession crawlSession);


    static final com.ten45.basic.Log log = com.ten45.basic.Log.getInstance( ConfigurationService.class );

}
