// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringServiceBase.vsl in andromda-spring-cartridge.
//
package com.ten45.manager.aggregator;

/**
 * <p>
 * Spring Service base class for <code>com.ten45.manager.aggregator.CrawlManager</code>,
 * provides access to all services and entities referenced by this service.
 * </p>
 *
 * @see com.ten45.manager.aggregator.CrawlManager
 */
public abstract class CrawlManagerBase
    extends com.ten45.manager.aggregator.AbstractAggregationManagerImpl
    implements com.ten45.manager.aggregator.CrawlManager
{

    private com.ten45.service.aggregator.ConfigurationService configurationService;

    /**
     * Sets the reference to <code>configurationService</code>.
     */
    public void setConfigurationService(com.ten45.service.aggregator.ConfigurationService configurationService)
    {
        this.configurationService = configurationService;
    }

    /**
     * Gets the reference to <code>configurationService</code>.
     */
    protected com.ten45.service.aggregator.ConfigurationService getConfigurationService()
    {
        return this.configurationService;
    }

    private com.ten45.service.aggregator.ProductFeedDeDupService productFeedDeDupService;

    /**
     * Sets the reference to <code>productFeedDeDupService</code>.
     */
    public void setProductFeedDeDupService(com.ten45.service.aggregator.ProductFeedDeDupService productFeedDeDupService)
    {
        this.productFeedDeDupService = productFeedDeDupService;
    }

    /**
     * Gets the reference to <code>productFeedDeDupService</code>.
     */
    protected com.ten45.service.aggregator.ProductFeedDeDupService getProductFeedDeDupService()
    {
        return this.productFeedDeDupService;
    }

    private com.ten45.service.aggregator.DerivationService derivationService;

    /**
     * Sets the reference to <code>derivationService</code>.
     */
    public void setDerivationService(com.ten45.service.aggregator.DerivationService derivationService)
    {
        this.derivationService = derivationService;
    }

    /**
     * Gets the reference to <code>derivationService</code>.
     */
    protected com.ten45.service.aggregator.DerivationService getDerivationService()
    {
        return this.derivationService;
    }

    private com.ten45.service.aggregator.NormalizationService normalizationService;

    /**
     * Sets the reference to <code>normalizationService</code>.
     */
    public void setNormalizationService(com.ten45.service.aggregator.NormalizationService normalizationService)
    {
        this.normalizationService = normalizationService;
    }

    /**
     * Gets the reference to <code>normalizationService</code>.
     */
    protected com.ten45.service.aggregator.NormalizationService getNormalizationService()
    {
        return this.normalizationService;
    }

    private com.ten45.manager.aggregator.HttpDownloadManager httpDownloadManager;

    /**
     * Sets the reference to <code>httpDownloadManager</code>.
     */
    public void setHttpDownloadManager(com.ten45.manager.aggregator.HttpDownloadManager httpDownloadManager)
    {
        this.httpDownloadManager = httpDownloadManager;
    }

    /**
     * Gets the reference to <code>httpDownloadManager</code>.
     */
    protected com.ten45.manager.aggregator.HttpDownloadManager getHttpDownloadManager()
    {
        return this.httpDownloadManager;
    }

    private com.ten45.service.aggregator.CrawlExtractionManager crawlExtractionManager;

    /**
     * Sets the reference to <code>crawlExtractionManager</code>.
     */
    public void setCrawlExtractionManager(com.ten45.service.aggregator.CrawlExtractionManager crawlExtractionManager)
    {
        this.crawlExtractionManager = crawlExtractionManager;
    }

    /**
     * Gets the reference to <code>crawlExtractionManager</code>.
     */
    protected com.ten45.service.aggregator.CrawlExtractionManager getCrawlExtractionManager()
    {
        return this.crawlExtractionManager;
    }

    private com.ten45.manager.aggregator.DomParsingManger domParsingManger;

    /**
     * Sets the reference to <code>domParsingManger</code>.
     */
    public void setDomParsingManger(com.ten45.manager.aggregator.DomParsingManger domParsingManger)
    {
        this.domParsingManger = domParsingManger;
    }

    /**
     * Gets the reference to <code>domParsingManger</code>.
     */
    protected com.ten45.manager.aggregator.DomParsingManger getDomParsingManger()
    {
        return this.domParsingManger;
    }

    private com.ten45.service.aggregator.CrawlDeDupService crawlDeDupService;

    /**
     * Sets the reference to <code>crawlDeDupService</code>.
     */
    public void setCrawlDeDupService(com.ten45.service.aggregator.CrawlDeDupService crawlDeDupService)
    {
        this.crawlDeDupService = crawlDeDupService;
    }

    /**
     * Gets the reference to <code>crawlDeDupService</code>.
     */
    protected com.ten45.service.aggregator.CrawlDeDupService getCrawlDeDupService()
    {
        return this.crawlDeDupService;
    }

    private com.ten45.manager.aggregator.ProductFeedManager productFeedManager;

    /**
     * Sets the reference to <code>productFeedManager</code>.
     */
    public void setProductFeedManager(com.ten45.manager.aggregator.ProductFeedManager productFeedManager)
    {
        this.productFeedManager = productFeedManager;
    }

    /**
     * Gets the reference to <code>productFeedManager</code>.
     */
    protected com.ten45.manager.aggregator.ProductFeedManager getProductFeedManager()
    {
        return this.productFeedManager;
    }

    private com.ten45.manager.staging.ProductStagingManager productStagingManager;

    /**
     * Sets the reference to <code>productStagingManager</code>.
     */
    public void setProductStagingManager(com.ten45.manager.staging.ProductStagingManager productStagingManager)
    {
        this.productStagingManager = productStagingManager;
    }

    /**
     * Gets the reference to <code>productStagingManager</code>.
     */
    protected com.ten45.manager.staging.ProductStagingManager getProductStagingManager()
    {
        return this.productStagingManager;
    }

    private com.ten45.entity.product.ProductCategoryDao productCategoryDao;

    /**
     * Sets the reference to <code>productCategory</code>'s DAO.
     */
    public void setProductCategoryDao(com.ten45.entity.product.ProductCategoryDao productCategoryDao)
    {
        this.productCategoryDao = productCategoryDao;
    }

    /**
     * Gets the reference to <code>productCategory</code>'s DAO.
     */
    protected com.ten45.entity.product.ProductCategoryDao getProductCategoryDao()
    {
        return this.productCategoryDao;
    }

    private com.ten45.entity.online.OnlineProductDao onlineProductDao;

    /**
     * Sets the reference to <code>onlineProduct</code>'s DAO.
     */
    public void setOnlineProductDao(com.ten45.entity.online.OnlineProductDao onlineProductDao)
    {
        this.onlineProductDao = onlineProductDao;
    }

    /**
     * Gets the reference to <code>onlineProduct</code>'s DAO.
     */
    protected com.ten45.entity.online.OnlineProductDao getOnlineProductDao()
    {
        return this.onlineProductDao;
    }

    /**
     * @see com.ten45.manager.aggregator.CrawlManager#StartCrawl(java.lang.Long, boolean)
     */
    public void StartCrawl(java.lang.Long CrawlSessionID, boolean isDebug)
    {
        if (CrawlSessionID == null)
        {
            throw new IllegalArgumentException(
                "com.ten45.manager.aggregator.CrawlManager.StartCrawl(java.lang.Long CrawlSessionID, boolean isDebug) - 'CrawlSessionID' can not be null");
        }
        try
        {
            this.handleStartCrawl(CrawlSessionID, isDebug);
        }
        catch (Throwable th)
        {
            throw new com.ten45.manager.aggregator.CrawlManagerException(
                "Error performing 'com.ten45.manager.aggregator.CrawlManager.StartCrawl(java.lang.Long CrawlSessionID, boolean isDebug)' --> " + th,
                th);
        }
    }

     /**
      * Performs the core logic for {@link #StartCrawl(java.lang.Long, boolean)}
      */
    protected abstract void handleStartCrawl(java.lang.Long CrawlSessionID, boolean isDebug)
        throws java.lang.Exception;

    /**
     * @see com.ten45.manager.aggregator.CrawlManager#StopAll()
     */
    public void StopAll()
    {
        try
        {
            this.handleStopAll();
        }
        catch (Throwable th)
        {
            throw new com.ten45.manager.aggregator.CrawlManagerException(
                "Error performing 'com.ten45.manager.aggregator.CrawlManager.StopAll()' --> " + th,
                th);
        }
    }

     /**
      * Performs the core logic for {@link #StopAll()}
      */
    protected abstract void handleStopAll()
        throws java.lang.Exception;

    /**
     * @see com.ten45.manager.aggregator.CrawlManager#LoadConfig()
     */
    public void LoadConfig()
    {
        try
        {
            this.handleLoadConfig();
        }
        catch (Throwable th)
        {
            throw new com.ten45.manager.aggregator.CrawlManagerException(
                "Error performing 'com.ten45.manager.aggregator.CrawlManager.LoadConfig()' --> " + th,
                th);
        }
    }

     /**
      * Performs the core logic for {@link #LoadConfig()}
      */
    protected abstract void handleLoadConfig()
        throws java.lang.Exception;

    /**
     * @see com.ten45.manager.aggregator.CrawlManager#getCrawlingSession()
     */
    public java.util.List<com.ten45.entity.aggregation.CrawlSessionImpl> getCrawlingSession()
    {
        try
        {
            return this.handleGetCrawlingSession();
        }
        catch (Throwable th)
        {
            throw new com.ten45.manager.aggregator.CrawlManagerException(
                "Error performing 'com.ten45.manager.aggregator.CrawlManager.getCrawlingSession()' --> " + th,
                th);
        }
    }

     /**
      * Performs the core logic for {@link #getCrawlingSession()}
      */
    protected abstract java.util.List<com.ten45.entity.aggregation.CrawlSessionImpl> handleGetCrawlingSession()
        throws java.lang.Exception;

    /**
     * @see com.ten45.manager.aggregator.CrawlManager#getToCrawlSessions()
     */
    public java.util.List<com.ten45.entity.aggregation.CrawlSessionImpl> getToCrawlSessions()
    {
        try
        {
            return this.handleGetToCrawlSessions();
        }
        catch (Throwable th)
        {
            throw new com.ten45.manager.aggregator.CrawlManagerException(
                "Error performing 'com.ten45.manager.aggregator.CrawlManager.getToCrawlSessions()' --> " + th,
                th);
        }
    }

     /**
      * Performs the core logic for {@link #getToCrawlSessions()}
      */
    protected abstract java.util.List<com.ten45.entity.aggregation.CrawlSessionImpl> handleGetToCrawlSessions()
        throws java.lang.Exception;

    /**
     * @see com.ten45.manager.aggregator.CrawlManager#stopCrawl(java.lang.Long)
     */
    public void stopCrawl(java.lang.Long crawlSessionID)
    {
        if (crawlSessionID == null)
        {
            throw new IllegalArgumentException(
                "com.ten45.manager.aggregator.CrawlManager.stopCrawl(java.lang.Long crawlSessionID) - 'crawlSessionID' can not be null");
        }
        try
        {
            this.handleStopCrawl(crawlSessionID);
        }
        catch (Throwable th)
        {
            throw new com.ten45.manager.aggregator.CrawlManagerException(
                "Error performing 'com.ten45.manager.aggregator.CrawlManager.stopCrawl(java.lang.Long crawlSessionID)' --> " + th,
                th);
        }
    }

     /**
      * Performs the core logic for {@link #stopCrawl(java.lang.Long)}
      */
    protected abstract void handleStopCrawl(java.lang.Long crawlSessionID)
        throws java.lang.Exception;

    /**
     * @see com.ten45.manager.aggregator.CrawlManager#resetCrawlSession(java.lang.Long)
     */
    public void resetCrawlSession(java.lang.Long crawlSessionID)
    {
        if (crawlSessionID == null)
        {
            throw new IllegalArgumentException(
                "com.ten45.manager.aggregator.CrawlManager.resetCrawlSession(java.lang.Long crawlSessionID) - 'crawlSessionID' can not be null");
        }
        try
        {
            this.handleResetCrawlSession(crawlSessionID);
        }
        catch (Throwable th)
        {
            throw new com.ten45.manager.aggregator.CrawlManagerException(
                "Error performing 'com.ten45.manager.aggregator.CrawlManager.resetCrawlSession(java.lang.Long crawlSessionID)' --> " + th,
                th);
        }
    }

     /**
      * Performs the core logic for {@link #resetCrawlSession(java.lang.Long)}
      */
    protected abstract void handleResetCrawlSession(java.lang.Long crawlSessionID)
        throws java.lang.Exception;

    /**
     * @see com.ten45.manager.aggregator.CrawlManager#discoverCrawlSessions()
     */
    public java.lang.Long discoverCrawlSessions()
    {
        try
        {
            return this.handleDiscoverCrawlSessions();
        }
        catch (Throwable th)
        {
            throw new com.ten45.manager.aggregator.CrawlManagerException(
                "Error performing 'com.ten45.manager.aggregator.CrawlManager.discoverCrawlSessions()' --> " + th,
                th);
        }
    }

     /**
      * Performs the core logic for {@link #discoverCrawlSessions()}
      */
    protected abstract java.lang.Long handleDiscoverCrawlSessions()
        throws java.lang.Exception;

    /**
     * @see com.ten45.manager.aggregator.CrawlManager#loadCrawlElements(java.lang.Long, java.lang.Integer)
     */
    public void loadCrawlElements(java.lang.Long crawlSessionID, java.lang.Integer crawlType)
    {
        if (crawlSessionID == null)
        {
            throw new IllegalArgumentException(
                "com.ten45.manager.aggregator.CrawlManager.loadCrawlElements(java.lang.Long crawlSessionID, java.lang.Integer crawlType) - 'crawlSessionID' can not be null");
        }
        if (crawlType == null)
        {
            throw new IllegalArgumentException(
                "com.ten45.manager.aggregator.CrawlManager.loadCrawlElements(java.lang.Long crawlSessionID, java.lang.Integer crawlType) - 'crawlType' can not be null");
        }
        try
        {
            this.handleLoadCrawlElements(crawlSessionID, crawlType);
        }
        catch (Throwable th)
        {
            throw new com.ten45.manager.aggregator.CrawlManagerException(
                "Error performing 'com.ten45.manager.aggregator.CrawlManager.loadCrawlElements(java.lang.Long crawlSessionID, java.lang.Integer crawlType)' --> " + th,
                th);
        }
    }

     /**
      * Performs the core logic for {@link #loadCrawlElements(java.lang.Long, java.lang.Integer)}
      */
    protected abstract void handleLoadCrawlElements(java.lang.Long crawlSessionID, java.lang.Integer crawlType)
        throws java.lang.Exception;

    /**
     * Gets the current <code>principal</code> if one has been set,
     * otherwise returns <code>null</code>.
     *
     * @return the current principal
     */
    protected java.security.Principal getPrincipal()
    {
        return com.ten45.PrincipalStore.get();
    }
}