// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package com.ten45.entity.aggregation;

/**
 * 
 */
public abstract class CrawlElement
    extends com.ten45.entity.EntityImpl
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -6101376523097834970L;




    private java.net.URL url;

    /**
     * 
     */
    public java.net.URL getUrl()
    {
        return this.url;
    }

    public void setUrl(java.net.URL url)
    {
        this.url = url;
    }


    private java.util.Date lastCrawledDate;

    /**
     * 
     */
    public java.util.Date getLastCrawledDate()
    {
        return this.lastCrawledDate;
    }

    public void setLastCrawledDate(java.util.Date lastCrawledDate)
    {
        this.lastCrawledDate = lastCrawledDate;
    }


    private java.lang.String element;

    /**
     * 
     */
    public java.lang.String getElement()
    {
        return this.element;
    }

    public void setElement(java.lang.String element)
    {
        this.element = element;
    }


    private java.lang.Long productID;

    /**
     * <p>
     * Product ID of the product in the database.
     * </p>
     */
    public java.lang.Long getProductID()
    {
        return this.productID;
    }

    public void setProductID(java.lang.Long productID)
    {
        this.productID = productID;
    }

    private com.ten45.entity.product.ProductCategory category;

    /**
     * 
     */
    public com.ten45.entity.product.ProductCategory getCategory()
    {
        return this.category;
    }

    public void setCategory(com.ten45.entity.product.ProductCategory category)
    {
        this.category = category;
    }

    private com.ten45.entity.aggregation.CrawlSession toCrawlSession;

    /**
     * 
     */
    public com.ten45.entity.aggregation.CrawlSession getToCrawlSession()
    {
        return this.toCrawlSession;
    }

    public void setToCrawlSession(com.ten45.entity.aggregation.CrawlSession toCrawlSession)
    {
        this.toCrawlSession = toCrawlSession;
    }

    private com.ten45.entity.aggregation.CrawlSession crawledSession;

    /**
     * 
     */
    public com.ten45.entity.aggregation.CrawlSession getCrawledSession()
    {
        return this.crawledSession;
    }

    public void setCrawledSession(com.ten45.entity.aggregation.CrawlSession crawledSession)
    {
        this.crawledSession = crawledSession;
    }

    /**
     * 
     */
    public abstract void dummy();

    /**
     * Returns <code>true</code> if the argument is an CrawlElement instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof CrawlElement))
        {
            return super.equals(object);
        }
        final CrawlElement that = (CrawlElement)object;
        if ( (this.id == null && that.getId() != null)
                || (this.id != null && that.getId() == null) 
                || (this.id != null && that.getId() != null
                        && !this.id.equals(that.getId())) )
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (id == null ? 0 : id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link com.ten45.entity.aggregation.CrawlElement}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link com.ten45.entity.aggregation.CrawlElement}.
         */
        public static com.ten45.entity.aggregation.CrawlElement newInstance()
        {
            return new com.ten45.entity.aggregation.CrawlElementImpl();
        }
    }

    protected static final com.ten45.basic.Log log = com.ten45.basic.Log.getInstance( CrawlElement.class );

// HibernateEntity.vsl merge-point
}