// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringHibernateDaoImpl.vsl in andromda-spring-cartridge.
//
package com.ten45.entity.aggregation;

import java.net.URL;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.hibernate.Query;

import com.ten45.domain.crawler.CategoryChecksumInfo;
import com.ten45.entity.product.ProductCategoryImpl;

/**
 * @see com.ten45.entity.aggregation.CrawlSession
 */
public class CrawlSessionDaoImpl
    extends com.ten45.entity.aggregation.CrawlSessionDaoBase
{
    
    protected CrawlSession handleFindCrawlSession(URL siteUrl) 
    throws java.lang.Exception 
    {
        /*
        String hql = "from CrawlSessionImpl crawlSession " +
        "where crawlSession.siteUrl = :siteUrl";

        Query query = this.getSession().createQuery(hql)
        .setParameter("siteUrl", siteUrl);

        java.util.List results = query.list();
        transformEntities(TRANSFORM_NONE, results);
        
        for (Object obj: results) {
            return (CrawlSession) obj;
         } */
        
        return null;
    }
}