//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package com.ten45.entity.aggregation;

import com.ten45.entity.product.ProductCategory;



/**
 * @see com.ten45.entity.aggregation.CrawlElement
 */
public class CrawlElementImpl
    extends com.ten45.entity.aggregation.CrawlElement
{
    /** 
     * The serial version UID of this class. Needed for serialization. 
     */
    private static final long serialVersionUID = 8128768123836470983L;
    
    public void dummy() {
        
    }
    
    public boolean equals(Object obj) {      
        //System.out.println("CrawlElement Equals Called.");
        
        if (obj == null) 
            return false;
        
        if (this == obj)
            return true;
        
        if (obj instanceof CrawlElement) {
            CrawlElement temp = (CrawlElement) obj;
            
            if (this.getUrl() != null && temp.getUrl() != null) {
                return this.getUrl().equals(temp.getUrl());
            }
            
            return this.getUrl() == temp.getUrl();
        }
        return false; 
    }
    
    public int hashCode() {
        if (super.getId() == null) {
            return 0;
        }
                
        //return (int) super.getId().intValue();
        return 0;
    } 
}