'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ScraperLibTest.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- BEGIN HEADER --&gt;
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;title&gt;Backcountry.com | Site Map Camp/Hike&lt;/title&gt;
        '''
        '''&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        '''
        '''&lt;script type=&quot;text/javascript&quot; src=&quot;http://akamai.backcountrystore.com.edgesuite.net/js/global/global.js&quot;&gt;&lt;/script&gt;
        '''
        '''	
        '''		&lt;script type=&quot;text/javascript&quot; src=&quot;http://akamai.backcountrystore.com.edgesuite.net/js/sites/bcs/site.js&quot;&gt;&lt;/script&gt;
        '''	
        '''	
        '''
        '''
        '''&lt;link rel=&quot;stylesheet&quot; href=&quot;http://akamai.backcountrystore.com.edgesuite.ne [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property html1() As String
            Get
                Return ResourceManager.GetString("html1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create Table TestTable
        '''(
        '''ID int IDENTITY(1,1) PRIMARY KEY,
        '''identifier1 text null,
        '''identifier2 text null,
        '''checksum1 text null,
        '''checksum2 text null,
        '''checksum3 text null
        ''')
        '''.
        '''</summary>
        Friend ReadOnly Property sqlExpressCreateTable() As String
            Get
                Return ResourceManager.GetString("sqlExpressCreateTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO [TestTable] ([identifier1], [identifier2], [checksum1], [checksum2], [checksum3]) VALUES (@identifier1, @identifier2, @checksum1, @checksum2, @checksum3);
        '''SELECT [ID], [identifier1], [identifier2], [checksum1], [checksum2], [checksum3] from [TestTable] Where (ID  = SCOPE_IDENTITY() );.
        '''</summary>
        Friend ReadOnly Property sqlExpressInsertSql() As String
            Get
                Return ResourceManager.GetString("sqlExpressInsertSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE [TestTable] SET [checksum1] = @checksum1, [checksum2] = @checksum2, [checksum3] = @checksum3 WHERE (identifier1 LIKE @identifier1) AND (identifier2 LIKE @identifier2);
        '''SELECT [ID], [identifier1], [identifier2], [checksum1], [checksum2], [checksum3] FROM [TestTable] WHERE ((identifier1 LIKE @identifier1) AND (identifier2 LIKE @identifier2));.
        '''</summary>
        Friend ReadOnly Property sqlExpressUpdateSql() As String
            Get
                Return ResourceManager.GetString("sqlExpressUpdateSql", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property test() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("test", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
