'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports ScraperLib





'''<summary>
'''This is a test class for ScraperLib.Cron and is intended
'''to contain all ScraperLib.Cron Unit Tests
'''</summary>
<TestClass()> _
Public Class CronTest


   Private testContextInstance As TestContext

   '''<summary>
   '''Gets or sets the test context which provides
   '''information about and functionality for the current test run.
   '''</summary>
   Public Property TestContext() As TestContext
      Get
         Return testContextInstance
      End Get
      Set(ByVal value As TestContext)
         testContextInstance = Value
      End Set
   End Property
#Region "Additional test attributes"
   '
   'You can use the following additional attributes as you write your tests:
   '
   'Use ClassInitialize to run code before running the first test in the class
   '
   '<ClassInitialize()>  _
   'Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
   'End Sub
   '
   'Use ClassCleanup to run code after all tests in a class have run
   '
   '<ClassCleanup()>  _
   'Public Shared Sub MyClassCleanup()
   'End Sub
   '
   'Use TestInitialize to run code before running each test
   '
   '<TestInitialize()>  _
   'Public Sub MyTestInitialize()
   'End Sub
   '
   'Use TestCleanup to run code after each test has run
   '
   '<TestCleanup()>  _
   'Public Sub MyTestCleanup()
   'End Sub
   '
#End Region


   '''<summary>
   '''A test for NextStartTime()
   '''</summary>
   <TestMethod()> _
   Public Sub NextStartTimeTest()
      Dim target As Cron = New Cron

      Console.WriteLine(target.NextStartTime)

      target.Minute = "0,30"

      Dim starTime As DateTime = New Date(2006, 10, 13, 13, 12, 0)
      Console.WriteLine("Start Time: " & starTime)

      Dim genDate As Date = target.getNextStartTime(starTime)
      Console.WriteLine(genDate)

      Assert.AreEqual(New Date(2006, 10, 13, 13, 30, 0), genDate, "The next date is not an expected date")

      For i As Integer = 0 To 9
         genDate = target.getNextStartTime(genDate)
         Console.WriteLine(genDate)
      Next


      target.Minute = "0"
      target.Hour = "0"
      target.DateOfMonth = "3-4"

      Console.WriteLine("Start Time: " & starTime)
      genDate = starTime
      For i As Integer = 0 To 9
         genDate = target.getNextStartTime(genDate)
         Console.WriteLine(genDate)
      Next


      target.Minute = "0"
      target.Hour = "0"
      target.DateOfMonth = "5"
      target.DayOfWeek = "1,2,3"

      Console.WriteLine("Start Time: " & starTime)
      Try
         genDate = starTime
         For i As Integer = 0 To 9
            genDate = target.getNextStartTime(genDate)
            Console.WriteLine(genDate)
         Next
      Catch ex As Exception
         Console.WriteLine("Invalid Cron")
      End Try



      'Assert.AreEqual(val, target.NextStartTime, "ScraperLib.Cron.NextStartTime was not set correctly.")
   End Sub

End Class
