'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports ScraperLib
Imports System.Drawing
Imports ScraperLibTest
Imports System.Windows.Forms

'''<summary>
'''This is a test class for ScraperLib.RTFEdit and is intended
'''to contain all ScraperLib.RTFEdit Unit Tests
'''</summary>
<TestClass()> _
Public Class RTFEditTest
   '''<summary>
   '''A test for RTFText()
   '''</summary>
   <TestMethod()> _
   Public Sub RTFTextTest()
      Dim target As RTFEdit = New RTFEdit
      Dim rtb As RichTextBox = New RichTextBox

      target.Text = "Small string test"
      rtb.Rtf = target.RTFText
      Assert.AreEqual(target.Text.Length, rtb.Text.Length, "Small string compare failed")


      Dim str As String = ""
      For i As Integer = 0 To 255
         str &= Chr(i) & Chr(i)
      Next

      rtb.Text = str
      str = rtb.Text

      target.Text = str
      rtb.Rtf = target.RTFText
      Assert.AreEqual(target.Text.Length, rtb.Text.Length, "Combination text compare failed.")

      rtb.Text = My.Resources.html1

      'Assert.AreEqual(My.Resources.html1.Length, rtb.Text.Length, "RTB text failed")
      str = rtb.Text

      target.Text = str
      rtb.Rtf = target.RTFText

      target.Text = rtb.Text
      rtb.Rtf = target.RTFText
      ' Perform lcs delta, find the text difference

      'Assert.AreEqual(target.Text.Length, rtb.Text.Length, "Big Html text - rtb -> rtbedit compare failed")

      target.Text = My.Resources.html1
      rtb.Rtf = target.RTFText
      'Assert.AreEqual(target.Text.Length, rtb.Text.Length, "Big Html text compare failed")
   End Sub

   Public Sub ColorTest()
      Dim target As RTFEdit = New RTFEdit
   End Sub
End Class
