'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ScraperLib.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System
        '''Imports Microsoft.VisualBasic
        '''Imports System.Text.RegularExpressions
        '''Imports DataRefinerAsm
        '''
        '''Public Class DefaultDataRefiner
        '''   Inherits DataRefinerAsm.DataRefiner
        '''
        '''   Public Overrides Function Refine(ByVal Text As String) As Object
        '''      Return text
        '''   End Function
        '''End Class
        '''.
        '''</summary>
        Friend ReadOnly Property DefaultDataRefiner() As String
            Get
                Return ResourceManager.GetString("DefaultDataRefiner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System
        '''Imports Microsoft.VisualBasic
        '''Imports System.Text.RegularExpressions
        '''Imports DataRefinerAsm
        '''
        '''Public Class DoubleDataRefiner
        '''   Inherits DataRefiner
        '''
        '''   Public Overrides Function Refine(ByVal text As String) As Object
        '''      Dim m As Match
        '''      m = Regex.Match(text, &quot;\d+\.\d+&quot;)
        '''
        '''      If m.Success Then
        '''         Return Double.Parse(m.Value)
        '''      Else
        '''         Return Nothing
        '''      End If
        '''   End Function
        '''End Class
        '''.
        '''</summary>
        Friend ReadOnly Property DoubleDataRefiner() As String
            Get
                Return ResourceManager.GetString("DoubleDataRefiner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System
        '''Imports Microsoft.VisualBasic
        '''Imports System.Text.RegularExpressions
        '''Imports DataRefinerAsm
        '''
        '''Public Class MoneyDataRefiner
        '''   Inherits DataRefiner
        '''
        '''   Public Overrides Function Refine(ByVal Text As String) As Object
        '''      Dim m As Match = Regex.Match(Text, &quot;\$.*?(\d+\.\d+)&quot;)
        '''
        '''      If m.Success Then
        '''         m = Regex.Match(m.Value, &quot;\d+\.\d+&quot;)
        '''
        '''         Return Double.Parse(m.Value)
        '''      End If
        '''
        '''      Return Nothing
        '''   End Function
        '''End Class
        '''.
        '''</summary>
        Friend ReadOnly Property MoneyDataRefiner() As String
            Get
                Return ResourceManager.GetString("MoneyDataRefiner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System
        '''Imports Microsoft.VisualBasic
        '''Imports System.Text.RegularExpressions
        '''Imports DataRefinerAsm
        '''
        '''Public Class NaturalNumberDataRefiner
        '''   Inherits DataRefiner
        '''
        '''   Public Overrides Function Refine(ByVal Text As String) As Object
        '''      Dim m As Match
        '''      m = Regex.Match(Text, &quot;\d+&quot;)
        '''
        '''      If m.Success Then
        '''         Return Double.Parse(m.Value)
        '''      Else
        '''         Return Nothing
        '''      End If
        '''   End Function
        '''End Class
        '''.
        '''</summary>
        Friend ReadOnly Property NaturalNumberDataRefiner() As String
            Get
                Return ResourceManager.GetString("NaturalNumberDataRefiner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System
        '''Imports Microsoft.VisualBasic
        '''Imports System.Text.RegularExpressions
        '''Imports DataRefinerAsm
        '''
        '''Public Class TextDataRefiner
        '''   Inherits DataRefinerAsm.DataRefiner
        '''
        '''   Public Overrides Function Refine(ByVal Text As String) As Object
        '''      Dim evl As New MatchEvaluator(AddressOf replaceFunction)
        '''      Return Regex.Replace(Text, &quot;([\s]+)&quot;, evl).Trim
        '''   End Function
        '''
        '''   Private Function replaceFunction(ByVal m As Match) As String
        '''      Return &quot; &quot;
        '''   End Function
        '''End Class
        '''.
        '''</summary>
        Friend ReadOnly Property TextDataRefiner() As String
            Get
                Return ResourceManager.GetString("TextDataRefiner", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
